name: Build NovaMind Lite OS (simple)

on:
  workflow_dispatch:

jobs:
  build-simple:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            live-build xorriso syslinux-common squashfs-tools debootstrap \
            ca-certificates parted grub-pc-bin grub-efi-amd64-bin \
            dosfstools mtools

      - name: Build ISO (force bookworm)
        run: |
          sudo rm -rf config/* cache/* chroot/* binary/* || true
          sudo lb clean || true
          sudo lb config --distribution bookworm \
            --mirror-bootstrap http://deb.debian.org/debian/ \
            --mirror-binary    http://deb.debian.org/debian/ \
            --mirror-chroot    http://deb.debian.org/debian/ \
            --mirror-chroot-security http://security.debian.org/debian-security/ \
            --mirror-binary-security http://security.debian.org/debian-security/
          sudo lb build
          ls -lh

      - name: Collect ISO
        run: |
          ISO=$(ls *.iso 2>/dev/null || ls live-image-*.iso 2>/dev/null || ls */*.iso 2>/dev/null)
          cp "$ISO" novamind-lite-os-live-amd64.iso
          ls -lh novamind-lite-os-live-amd64.iso

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: novamind-lite-os-live-amd64
          path: novamind-lite-os-live-amd64.iso
