name: Build NovaMind Lite OS ISO

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build xorriso syslinux-common squashfs-tools debootstrap ca-certificates
      - name: Build ISO
        run: |
          cd novamind-lite-livebuild-latest
          chmod +x build.sh
          ./build.sh
          ls -lh
      - name: Collect ISO
        run: |
          ISO=$(ls novamind-lite-livebuild-latest/*.iso || ls novamind-lite-livebuild-latest/live-image-*.iso)
          cp "$ISO" novamind-lite-os-live-amd64.iso
          ls -lh
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: novamind-lite-os-live-amd64
          path: novamind-lite-os-live-amd64.iso
