name: Build NovaMind Lite OS ISO

on:
  workflow_dispatch:

jobs:
  build-simple:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y \
            live-build xorriso squashfs-tools debootstrap \
            ca-certificates parted grub-pc-bin grub-efi-amd64-bin \
            dosfstools mtools debian-archive-keyring

      - name: Build ISO (UEFI + BIOS, Debian Bookworm)
        run: |
          set -Eeuo pipefail
          trap 'echo "::error ::Build ISO failed on line $LINENO"' ERR

          # clean previous artifacts
          sudo rm -rf config/apt config/archives/*.chroot cache chroot binary || true
          sudo lb clean || true

          # APT settings inside chroot (disable Contents indexes to avoid 404)
          sudo install -d -m 0755 config/apt
          {
            echo 'Acquire::Retries "5";'
            echo 'Acquire::http::Pipeline-Depth "0";'
            echo 'Acquire::Languages "none";'
            echo 'Acquire::GzipIndexes "false";'
            echo 'Acquire::CompressionTypes::Index:: "xz";'
            echo 'Acquire::IndexTargets::deb::Contents "false";'
          } | sudo tee config/apt/apt.conf.chroot >/dev/null

          # Pin Debian sources (no heredoc!)
          sudo install -d -m 0755 config/archives
          sudo bash -c 'printf "%s\n" \
            "deb https://deb.debian.org/debian bookworm main contrib non-free non-free-firmware" \
            "deb https://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware" \
            > config/archives/debian.list.chroot'
          echo 'deb https://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware' \
            | sudo tee config/archives/security.list.chroot >/dev/null

          # Ensure debootstrap trusts Debian archives
          echo 'debian-archive-keyring' | sudo tee config/bootstrap-include >/dev/null

          # Configure live-build: UEFI boot via GRUB, BIOS via GRUB-PC, plain ISO
          sudo lb config \
            --mode debian \
            --distribution bookworm \
            --archive-areas "main contrib non-free non-free-firmware" \
            --security false \
            --mirror-bootstrap https://deb.debian.org/debian \
            --mirror-chroot    https://deb.debian.org/debian \
            --mirror-binary    https://deb.debian.org/debian \
            --mirror-chroot-security https://security.debian.org/debian-security \
            --mirror-binary-security https://security.debian.org/debian-security \
            --binary-images iso \
            --bootloader grub-efi \
            --uefi-secure-boot enable \
            --linux-flavours amd64 \
            --linux-packages "linux-image" \
            --bootappend-live "boot=live components quiet splash"

          echo "==== archives in chroot ===="
          sudo find config/archives -maxdepth 1 -type f -name '*.chroot' -print -exec cat {} \;

          echo "==== apt.conf.chroot ===="
          sudo cat config/apt/apt.conf.chroot || true

          sudo lb build
          ls -lh

      - name: Collect ISO
        run: |
          set -e
          ISO=$(ls *.iso 2>/dev/null || ls live-image-*.iso 2>/dev/null || ls */*.iso 2>/dev/null)
          [ -n "$ISO" ]
          cp "$ISO" novamind-lite-os-live-amd64.iso
          sha256sum novamind-lite-os-live-amd64.iso > novamind-lite-os-live-amd64.sha256
          ls -lh novamind-lite-os-live-amd64.iso novamind-lite-os-live-amd64.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: novamind-lite-os-live-amd64
          path: |
            novamind-lite-os-live-amd64.iso
            novamind-lite-os-live-amd64.sha256
